on: push
name: Push Checks
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run test:coverage
      - name: Fix Code Coverage Paths
        # https://community.sonarsource.com/t/code-coverage-doesnt-work-with-github-action/16747
        working-directory: ./coverage
        run: |
          sed -i "s@${GITHUB_WORKSPACE}@/github/workspace/@g" lcov.info
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./lcov.info
  lint:
    name: Lint, Check Types, Check Deps, Build
    runs-on: ubuntu-latest
    env:
      GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: node_cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          # no restore-keys as we want an exact match or rebuild
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm ci
      # - run: npm run lint
      - run: npm run check-types
