on: push
name: Push Checks
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run test:coverage
      - name: Code Coverage Report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Lint, Check Types, Check Deps, Build
    runs-on: ubuntu-latest
    env:
      GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: node_cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          # no restore-keys as we want an exact match or rebuild
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      # - run: npm run lint
      - run: npm run check-types
